In [1]:
a=[3,4,5,6,7,8,9]
a

[3, 4, 5, 6, 7, 8, 9]

In [2]:
import numpy as np

In [3]:
a1=np.array([3, 4, 5, 6, 7, 8, 9])
a1

array([3, 4, 5, 6, 7, 8, 9])

In [4]:
a1+2

array([ 5,  6,  7,  8,  9, 10, 11])

## Numpy: Numerical Pyhton
**Why Numpy?**
* It is used for performing operations like array Addition, subtraction, multiplication,to create some Random numbers, create dummy values etc,.

#### List Vs Array 
* In list we cannot do element-wise operation but in array we can
* Array to list conversion is possible and also list to array conversion it also possible but we will lose the dimension.
* List is heterogenous datatype but numpy is a homogenous datatype.


In [5]:
arr1 = np.array(['Deepak',12,4.5,True,567])
arr1

array(['Deepak', '12', '4.5', 'True', '567'], dtype='<U32')

In [10]:
arr2=([2,45,56,78,89,567,12.4])
arr2


[2, 45, 56, 78, 89, 567, 12.4]

In [14]:
arr3=np.array([12,34.7,68,26.9])
arr3

array([12. , 34.7, 68. , 26.9])

In [16]:
arr4=np.array([2,4,5,6,7,8,9,])
arr4

array([2, 4, 5, 6, 7, 8, 9])

In [20]:
type(arr3)

numpy.ndarray

In [21]:
arr4.dtype

dtype('int64')

In [22]:
arr4.ndim

1

In [23]:
arr4.size

7

In [24]:
arr4.shape

(7,)

In [25]:
arr5=np.array([[1,2,3,4,5,6]])
arr5

array([[1, 2, 3, 4, 5, 6]])

In [26]:
arr5.ndim

2

In [29]:
arr6=np.array([[2,4,6],[1,2,7],[5,8,9]])
arr6

array([[2, 4, 6],
       [1, 2, 7],
       [5, 8, 9]])

In [30]:
arr6.shape

(3, 3)

In [31]:
arr6.ndim

2

In [32]:
arr6[1][2]

np.int64(7)

In [34]:
arr6[1,2]

np.int64(7)

In [35]:
arr6[:2:,0:2:]

array([[2, 4],
       [1, 2]])

In [39]:
arr6[1,1]=20

In [40]:
arr6

array([[ 2,  4,  6],
       [ 1, 20,  7],
       [ 5,  8,  9]])

In [49]:
# between 1 to 50 generate random 10 values
rand=np.random.randint(1,50,10)

In [46]:
np.random.choice(np.arange(1,51),10)

array([26, 36,  8, 31,  6, 17, 35, 20,  4,  6])

In [48]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [50]:
rand

array([ 8, 44, 31, 23, 39, 33, 47, 11, 26, 43], dtype=int32)

In [51]:
rand.reshape(2,5)

array([[ 8, 44, 31, 23, 39],
       [33, 47, 11, 26, 43]], dtype=int32)

In [53]:
np.reshape(rand,(2,5))

array([[ 8, 44, 31, 23, 39],
       [33, 47, 11, 26, 43]], dtype=int32)

In [ ]:
Zeros 
ones 
identity
7 matrix

In [57]:
np.zeros((3,6),dtype='int')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [58]:
np.ones((2,4),dtype='int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [59]:
np.eye(3,dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [60]:
np.identity(7,dtype='int')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [64]:
temp=np.full((3,3),7)

In [65]:
temp.reshape(9,)

array([7, 7, 7, 7, 7, 7, 7, 7, 7])

In [66]:
temp.flatten()

array([7, 7, 7, 7, 7, 7, 7, 7, 7])

In [70]:
a3=np.array([[1,2],[7,8]])
a3

array([[1, 2],
       [7, 8]])

In [72]:
a4=np.array([[4,9],[2,5]])
a4

array([[4, 9],
       [2, 5]])

In [73]:
a3+a4

array([[ 5, 11],
       [ 9, 13]])

In [74]:
np.matmul(a3,a4)

array([[  8,  19],
       [ 44, 103]])

In [ ]:
universal functions
sqrt()
exp()
lop()
sin()
mean()
median()
std()